### PR TITLE
Ukrainian

### PR DESCRIPTION
**Pull request by lolobosse**
Hi all,

Thanks @immoroz for the work, I just formatted properly.

Is it ok @hustcc ?

Best,

Laurent

### CODE REVIEW

**Comment by hustcc** [comment]
seems has conflict~

**Comment by lolobosse** [comment]
image

I solved the conflicts, that's why I dropped the previous PR: I also merged arabic in this PR so I do not think that there is any conflict 🤷‍♂ What do you mean?

**Comment by lolobosse** [comment]
@hustcc What do you think? Did I miss something? Merry Xmas :christmas_tree: BTW

**Comment by hustcc** [comment]
👍🏻👌🏻，Thanks for your work.

**Pull request merged**
