### PR TITLE
Locale hindi and bengali

### PR DESCRIPTION
**Pull request by ajphukan**
Two more language for locale

### CODE REVIEW

**Comment by hustcc** [comment]
I am very sorry. 

Now the code of timeago is not very perfect, I will chang it like [timeago.js](https://github.com/hustcc/timeago.js), so just wait for a while.

**Comment by hustcc** [comment]
Thank you very much, if add some testcase will be perfact.

**Comment by ajphukan** [comment]
Can you explain or give the line number of the code to change ...

**Comment by hustcc** [comment]
You can run

```sh
./test/do_test.sh
```
to run testcase.

for locale test, you can write a new test file in `test/locales/` dir, and add 

```py
python test/locales/<locale_name>.py
```` 
into `test/do_test.sh`.

**Comment by ajphukan** [comment]
means i have to write the whole test file like the eng test case ...

**Comment by hustcc** [comment]
yes ^_^

**Comment by ajphukan** [comment]
okk let me write the test case first .. if you need help to port local
files from timeago.js to timeago ...

**Comment by jace** [comment]
These locale files are incorrectly named. They should be `hi_IN.py` or `hi.py` (Hindi) and `bn_IN.py` (Bengali). `IN` is the country code and not the language code, so it should appear second. Bengali is `bn`, not `bg`.

**Pull request merged**
