### PR TITLE
PL rewrite

### PR DESCRIPTION
**Pull request by lolobosse**
Hey, I saw that #23 wasn't merging because of some issues with external grammar files so I tried to fix them.

Could @hustcc, @marcel-odya and others took a look at it?

I'm not extremely proud of the design but it does the work and the whole locale logic lives in one and only file. 💪 

Btw @marcel-odya, thanks for the work, it was awesome! 👍 🙏

### CODE REVIEW

**Comment by hustcc** [comment]
I have not write `python` for years, do you has some time to maintain the librarr, include:

 - issue and pr
 - version release

**Comment by lolobosse** [comment]
@hustcc I'm already maintainer of the project, but you had some issues with the existing PR; that's why I'm asking if it suits better. If yes, I'll release `1.0.9` with PL in it.

**Comment by marcel-odya** [comment]
Sorry guys for not giving feedback earlier. I've been pretty busy these days.
@lolobosse it looks great if you ask me. I guess it's better that way, regarding it all sits in one file now and is easier to grasp.

**Comment by marcel-odya** [comment]
Sorry guys for not giving feedback earlier. I've been pretty busy these days.
@lolobosse it looks great if you ask me. I guess it's better that way, regarding it all sits in one file now and is easier to grasp.

**Pull request merged**
